build:
  script:
    - npm install
    - npx --cache ./npm_cache vsce package -o cad.vsix
  cache:
    paths:
      - npm_cache
      - node_modules
  artifacts:
    paths:
      - '*.vsix'
    expire_in: 3 months
  only:
    - tags
  